import './globals.css'
import { ReactNode } from 'react'
import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="m-3">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
